aldryn_blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from aldryn_blog.views import (
    ArchiveView, PostDetailView, TaggedListView, AuthorEntriesView,
    TagsListView, AuthorsListView, CategoryListView, CategoryPostListView)
from aldryn_blog.feeds import LatestEntriesFeed, TagFeed, CategoryFeed

urlpatterns = patterns(
    '',
    url(r'^$', ArchiveView.as_view(), name='latest-posts'),
    url(r'^author/$', AuthorsListView.as_view(), name='author-list'),
    url(r'^author/(?P<slug>[\w.@+-]+)/$', AuthorEntriesView.as_view(), name='author-posts'),
    url(r'^feed/$', LatestEntriesFeed(), name='latest-posts-feed'),
    url(r'^(?P<year>\d{4})/$', ArchiveView.as_view(), name='archive-year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', ArchiveView.as_view(), name='archive-month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', ArchiveView.as_view(), name='archive-day'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$', PostDetailView.as_view(), name='post-detail'),
    url(r'^category/$', CategoryListView.as_view(), name='category-list'),
    url(r'^category/(?P<category>[-\w]+)/$', CategoryPostListView.as_view(), name='category-posts'),
    url(r'^category/(?P<category>[-\w]+)/feed/$', CategoryFeed(), name='category-posts-feed'),
    url(r'^tag/$', TagsListView.as_view(), name='tag-list'),
    url(r'^tag/(?P<tag>[-\w]+)/$', TaggedListView.as_view(), name='tagged-posts'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$', TagFeed(), name='tagged-posts-feed'),
)

aldryn_blog/models.py
# -*- coding: utf-8 -*-
import datetime
from collections import Counter

from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse, NoReverseMatch
from django.db import models
from django.db.models import Q
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils.translation import get_language, ugettext_lazy as _, override

from app_data import AppDataField
from cms.utils.i18n import get_current_language
from cms.models.fields import PlaceholderField
from cms.models.pluginmodel import CMSPlugin
from djangocms_text_ckeditor.fields import HTMLField
from filer.fields.image import FilerImageField
from hvad.models import TranslationManager, TranslatableModel, TranslatedFields
from taggit.managers import TaggableManager
from taggit.models import TaggedItem, Tag

from .conf import settings
from .utils import generate_slugs, get_blog_authors, get_slug_for_user, get_slug_in_language


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class CategoryManager(TranslationManager):

    def get_with_usage_count(self, language=None, **kwargs):
        categories = list(self.language(language).filter(**kwargs).distinct())

        # No annotate in hvad
        for category in categories:
            category.post_count = category.post_set.count()
        return sorted(categories, key=lambda x: -x.post_count)


class Category(TranslatableModel):

    translations = TranslatedFields(
        name=models.CharField(_('Name'), max_length=255),
        slug=models.SlugField(_('Slug'), max_length=255, blank=True,
                              help_text=_('Auto-generated. Clean it to have it re-created. '
                                          'WARNING! Used in the URL. If changed, the URL will change. ')),
        meta={'unique_together': [['slug', 'language_code']]}
    )

    ordering = models.IntegerField(_('Ordering'), default=0)

    objects = CategoryManager()

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['ordering']

    def __unicode__(self):
        return self.lazy_translation_getter('name', str(self.pk))

    def get_absolute_url(self, language=None):
        language = language or get_current_language()
        slug = get_slug_in_language(self, language)
        with override(language):
            if slug:
                return reverse('aldryn_blog:category-posts', kwargs={'category': slug})

            # category not translated in given language
            try:
                return reverse('aldryn_blog:latest-posts')
            except (ImproperlyConfigured, NoReverseMatch):
                return '/%s' % language


class RelatedManager(models.Manager):

    def get_query_set(self):
        qs = super(RelatedManager, self).get_query_set()
        return qs.select_related('key_visual')

    def filter_by_language(self, language):
        qs = self.get_query_set()
        return qs.filter(Q(language__isnull=True) | Q(language=language))

    def filter_by_current_language(self):
        return self.filter_by_language(get_language())

    def get_tags(self, entries=None, language=None):
        """Returns tags used to tag post and its count. Results are ordered by count."""

        if not entries:
            entries = self

        if language:
            entries = entries.filter_by_language(language)
        entries = entries.distinct()
        if not entries:
            return []
        kwargs = TaggedItem.bulk_lookup_kwargs(entries)

        # aggregate and sort
        counted_tags = dict(TaggedItem.objects
                                      .filter(**kwargs)
                                      .values('tag')
                                      .annotate(count=models.Count('tag'))
                                      .values_list('tag', 'count'))

        # and finally get the results
        tags = Tag.objects.filter(pk__in=counted_tags.keys())
        for tag in tags:
            tag.count = counted_tags[tag.pk]
        return sorted(tags, key=lambda x: -x.count)

    def get_categories(self, language=None):
        """
        Returns all categories used in posts and the amount, ordered by amount.
        """

        entries = (self.filter_by_language(language) if language else self).distinct()
        if not entries:
            return Category.objects.none()

        return Category.objects.filter(post__in=entries).annotate(count=models.Count('post')).order_by('-count')

    def get_months(self, language):
        """Get months with aggregatet count (how much posts is in the month). Results are ordered by date."""
        # done via naive way as django's having tough time while aggregating on date fields
        entries = self.filter_by_language(language)
        dates = entries.values_list('publication_start', flat=True)
        dates = [(x.year, x.month) for x in dates]
        date_counter = Counter(dates)
        dates = set(dates)
        dates = sorted(dates, reverse=True)
        return [{'date': datetime.date(year=year, month=month, day=1),
                 'count': date_counter[year, month]} for year, month in dates]


class PublishedManager(RelatedManager):

    def get_query_set(self):
        qs = super(PublishedManager, self).get_query_set()
        now = timezone.now()
        qs = qs.filter(publication_start__lte=now)
        qs = qs.filter(Q(publication_end__isnull=True) | Q(publication_end__gte=now))
        return qs


class Post(models.Model):

    title = models.CharField(_('Title'), max_length=255)
    slug = models.CharField(_('Slug'), max_length=255, unique=True, blank=True,
                            help_text=_('Used in the URL. If changed, the URL will change. '
                                        'Clean it to have it re-created.'))
    language = models.CharField(_('language'), max_length=5, null=True, blank=True, choices=settings.LANGUAGES,
                                help_text=_('leave empty to display in all languages'))
    key_visual = FilerImageField(verbose_name=_('Key Visual'), blank=True, null=True)
    lead_in = HTMLField(_('Lead-in'),
                        help_text=_('Will be displayed in lists, and at the start of the detail page (in bold)'))
    content = PlaceholderField('aldryn_blog_post_content', related_name='aldryn_blog_posts')
    author = models.ForeignKey(to=AUTH_USER_MODEL, verbose_name=_('Author'))
    coauthors = models.ManyToManyField(
        to=AUTH_USER_MODEL, verbose_name=_('Co-Authors'), null=True, blank=True, related_name='aldryn_blog_coauthors')
    publication_start = models.DateTimeField(_('Published Since'), default=timezone.now,
                                             help_text=_('Used in the URL. If changed, the URL will change.'))
    publication_end = models.DateTimeField(_('Published Until'), null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name=_('Category'), null=True, blank=True)

    objects = RelatedManager()
    published = PublishedManager()
    tags = TaggableManager(blank=True)
    app_data = AppDataField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {'year': self.publication_start.year,
                  'month': self.publication_start.month,
                  'day': self.publication_start.day,
                  'slug': self.slug}
        if self.language and not getattr(settings, 'ALDRYN_BLOG_SHOW_ALL_LANGUAGES', False):
            with override(self.language):
                return reverse('aldryn_blog:post-detail', kwargs=kwargs)
        return reverse('aldryn_blog:post-detail', kwargs=kwargs)

    class Meta:
        ordering = ['-publication_start']

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Post, self).save(**kwargs)

    def get_author_slug(self):
        # FIXME: This is a potential performance hogger
        return get_slug_for_user(self.author)


class LatestEntriesPlugin(CMSPlugin):

    latest_entries = models.IntegerField(default=5, help_text=_('The number of latests entries to be displayed.'))
    tags = models.ManyToManyField('taggit.Tag', blank=True, help_text=_('Show only the blog posts tagged with chosen tags.'))

    def __unicode__(self):
        """
        must return a unicode string
        """
        return str(self.latest_entries).decode('utf8')

    def copy_relations(self, oldinstance):
        self.tags = oldinstance.tags.all()

    def get_posts(self):
        posts = Post.published.filter_by_language(self.language)
        tags = list(self.tags.all())
        if tags:
            posts = posts.filter(tags__in=tags)
        return posts[:self.latest_entries]


class AuthorsPlugin(CMSPlugin):
    def get_authors(self):
        return generate_slugs(get_blog_authors())


def force_language(sender, instance, **kwargs):
    if issubclass(sender, CMSPlugin) and instance.placeholder and instance.placeholder.slot == 'aldryn_blog_post_content':
        instance.language = settings.ALDRYN_BLOG_PLUGIN_LANGUAGE


for model in CMSPlugin.__subclasses__():
    models.signals.pre_save.connect(force_language, sender=model)

aldryn_blog/templates/aldryn_blog/author_list.html
{% extends "aldryn_blog/base.html" %}
{% load i18n thumbnail aldryn_blog_tags %}
{% load url from future %}

{% block content_blog %}
<div class="blog-list">
    {% block blog_title %}<h2>{% trans "Blog Authors" %}</h2>{% endblock %}
    <ul class="blog-authors">
        {% for author in object_list %}
        <li><a href="{% url 'aldryn_blog:author-posts' author.slug %}">{{ author.get_full_name }} ({{ author.post_set.count }} articles)</a></li>
        {% empty %}
        <li class="blog-empty"><p>{% trans "No entry found." %}</p></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

aldryn_blog/templates/aldryn_blog/base.html
{% extends "base.html" %}

{% block extend_breadcrumb %}
    {{ block.super }}
    {% block blog_breadcrumb %}
    {% endblock blog_breadcrumb %}
{% endblock extend_breadcrumb%}

{% block content %}
<div class="app app-blog">
    {% block content_blog %}{% endblock %}
</div>
{% endblock %}

aldryn_blog/templates/aldryn_blog/category_list.html
{% extends "aldryn_blog/base.html" %}
{% load i18n thumbnail aldryn_blog_tags %}
{% load url from future %}

{% block content_blog %}
<div class="blog-list">
    {% block blog_title %}<h2>{% trans "Blog Categories" %}</h2>{% endblock %}
    <ul class="blog-categories">
        {% for category in object_list %}
        <li><a href="{% url 'aldryn_blog:category-posts' category=category.slug %}" class="blog-category-{{ category.count }}">{{ category.name }} <span>({{ category.count }})</span></a></li>
        {% empty %}
        <li class="blog-empty"><p>{% trans "No entry found." %}</p></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

aldryn_blog/templates/aldryn_blog/post_archive.html
{% extends "aldryn_blog/post_list.html" %}

aldryn_blog/templates/aldryn_blog/post_detail.html
{% extends "aldryn_blog/base.html" %}
{% load i18n thumbnail cms_tags aldryn_blog_tags %}
{% load url from future %}

{% block content_blog %}
<div class="blog-detail">
    {% block blog_title %}<h2>{% render_model post "title" %}</h2>{% endblock %}
    {% if post.key_visual_id %}<p class="blog-visual"><img src="{% thumbnail post.key_visual 660x200 crop subject_location=post.key_visual.subject_location %}" alt="" /></p>{% endif %}
    <span class="blog-author">
        {% trans "by" %} {{ post.author|user_name }}{% if post.coauthors.exists %},
            {% for coauthor in post.coauthors.all %}
                {{ coauthor|user_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        {% endif %}
    </span>
    <div class="blog-lead">{% render_model post "lead_in" "lead_in" "" safe %}</div>
    <div class="blog-content">{% render_placeholder post.content language placeholder_language %}</div>
    <p class="blog-back"><a href="{% url 'aldryn_blog:latest-posts' %}">{% trans "Back" %}</a></p>
</div>
{% endblock %}

aldryn_blog/templates/aldryn_blog/post_list.html
{% extends "aldryn_blog/base.html" %}
{% load i18n thumbnail aldryn_blog_tags %}

{% block blog_breadcrumb %}
    <li><span class="separator">&raquo;</span></li>
    {% if author %}
        <li><span>{{ author.get_full_name }}</span></li>
    {% elif archive_date %}
        {% if year and month and day %}
            <li><a href="{% url 'aldryn_blog:archive-year' year=year %}">{{ year }}</a> <span class="separator">&raquo;</span></li>
            <li><a href="{% url 'aldryn_blog:archive-month' year=year month=month %}">{{ month }}</a> <span class="separator">&raquo;</span></li>
            <li><span>{{ day }}</span></li>
        {% elif year and month %}
            <li><a href="{% url 'aldryn_blog:archive-year' year=year %}">{{ year }}</a> <span class="separator">&raquo;</span></li>
            <li><span>{{ month }}</span></li>
        {% elif year %}
            <li><span>{{ year }}</span></li>
        {% endif %}
    {% elif tagged_entries %}
            <li><span>{{ tagged_entries|capfirst }}</span></li>
    {% endif %}
{% endblock blog_breadcrumb %}

{% block content_blog %}
<div class="blog-list">
    {% block blog_title %}<h2>
        {% if author %}{% trans "Entries by" %} {{ author.get_full_name }}{% elif archive_date %}
        {% trans "Blog Archive" %} &ndash; {% if day %}{{ archive_date|date:'d' }}. {% endif %}{% if month %}{{ archive_date|date:'F' }} {% endif %}{{ year }}{% elif tagged_entries %}
        {% trans "Blog Tag" %} &ndash; {{ tagged_entries|capfirst }}{% else %}
        {% trans "Blog" %}{% endif %}</h2>{% endblock %}
    {% include "aldryn_blog/includes/blog_items.html" with posts=latest|posts:object_list image="true" %}
    {% include "aldryn_common/paginator.html" %}
    {% if author or archive_date or tagged_entries %}
    <p class="blog-back"><a href="{% url 'aldryn_blog:latest-posts' %}">{% trans "Back" %}</a></p>
    {% endif %}
</div>
{% endblock %}

aldryn_blog/templates/aldryn_blog/tag_list.html
{% extends "aldryn_blog/base.html" %}
{% load i18n thumbnail aldryn_blog_tags %}
{% load url from future %}

{% block content_blog %}
<div class="blog-list">
    {% block blog_title %}<h2>{% trans "Blog Tags" %}</h2>{% endblock %}
    <ul class="blog-tags">
        {% for tag in object_list %}
        <li><a href="{% url 'aldryn_blog:tagged-posts' tag=tag.slug %}" class="blog-tag-{{ tag.count }}">{{ tag.name }} <span>({{ tag.count }})</span></a></li>
        {% empty %}
        <li class="blog-empty"><p>{% trans "No entry found." %}</p></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}